# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nomnom9.2' do
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nomnom9.2

  target 'nomnom9.2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nomnom9.2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
